# we create a Docker image from source code
version : "3.8"
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB : testdb
    networks:
      - nestjs-network
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  nestjs-network:
volumes:
  pgdata:
# Create container, network,.. from "docker composer" file:
# -d: deamon/background mode
# docker compose up -d
# if u want to start only specified services/container:
# docker compose up -d dev-database -d
# access to db
# docker exec -it dev-database bash
# how to remove containers+volumes
# docker compose rm dev-database --stop --force --volumes